### ISSUE TITLE
Tools?

### ISSUE THREAD

**Issue by remorse** [brandon-rhodes/Concentric-CSS#10]
Hi! Do you know of any command-line tools that can be used to enforce this ordering on CSS?

Thanks,
Ricky

**Comment by bartveneman** [comment]
This should help: https://www.npmjs.com/package/stylelint-order

**Comment by brandon-rhodes** [comment]
No, I'm not remembering any automated tools that enforce order, but it's possible that they exist in the ecosystem without my having run across them.

**Comment by brandon-rhodes** [comment]
I'm closing this issue for now, but anyone should feel free to make further comments with links as you run across tools that might satisfy this question. Thanks!

**Comment by ataylor32** [comment]
https://www.npmjs.com/package/css-declaration-sorter

**Comment by brandon-rhodes** [comment]
Thanks for the link, I hadn't come across that tool before.
