### ISSUE TITLE
CSS3 Property List to add

### ISSUE THREAD

**Issue by dantesolis** [brandon-rhodes/Concentric-CSS#4]
This is issue is just as a reference for the future PR. List of new CSS3 props

- [x] Animation
- [x] Background
- [x] Border
- [x] Color
- [x] Dimensions
- [x] Generated Content
- [x] Flexbox
- [x] Font
- [x] List
- [x] Margin
- [x] Multi-Column
- [x] Outline
- [x] Padding
- [x] Print
  - [x] `page-break-[before|after]` to be changed for `break-[before|after]` - Added as a reference, but should be change in the future.
- [x] Table
- [x] Text
- [x] Transform
- [x] Transitions
- [x] Visuals

**Comment by brandon-rhodes** [comment]
Thanks for the pull request! As it looks like you completed this entire checklist and the result is now merged, I'll go ahead and close this issue — let me know if you think of further tweaks!
